// Generated by tools/gen_bloub_tables.py -- do not edit by hand.
// Regenerate with: python3 tools/gen_bloub_tables.py
//
// Source of truth: reference/bloub/src/bot/eyefit.ts.

#pragma once

#include "bloub_skins.h"
#include "bloub_states.h"

// Eye-fit offsets, in ball-radius units.
//
// The eyes live on a sphere and `profile_radius_at` sticks them back onto the
// real outline pro rata of the local radius. That pro-rata places their CENTRE
// correctly, but an eye has a size, and the margin it has left in front of the
// edge is multiplied by the same factor -- so a silhouette that is narrow in the
// eye's direction pushes it through the edge. This table holds the common
// translation to apply to BOTH eyes, which is an isometry: spacing, sizes and
// tilts survive to the pixel.
//
// It is a table and not a solver, and that distinction IS the fix. Solved in the
// render loop it reacts to everything that moves at sixty frames a second, and
// every one of the seven variants written that way trembled. See eyefit.ts.

#define BLOUB_EYEFIT_COLUMNS 37
#define BLOUB_EYEFIT_EXPRESSIONS 16

extern const float BLOUB_EYEFIT[GROK_SHAPE_COUNT][BLOUB_EYEFIT_COLUMNS][2];

typedef struct {
    float x, y;
} bloub_vec2_t;

/**
 * Offset for this shape on this state and expression.
 *
 * Zero as soon as the shape is not one of the customiser's (which covers
 * GROK_FACE_SHAPE_NONE and the circle, whose two profiles are the same), and zero
 * on any state that does not carry the resting body. A state without the resting
 * FACE has a single entry, whatever the expression.
 */
bloub_vec2_t bloub_eyefit(int shape, bloub_state_id_t state, int expr);
