#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "bloub_shapes.h"

// Orbit rings, the "play" swoosh, comet ribbons, burst particles, and the
// three-dot "thinking" positions/sizes. Ported from bloub's src/bot/decor.ts.
// The ring/swoosh/comet/particle tables were generated by evaluating the
// original mulberry32-seeded TypeScript once (see the dump script used while
// porting) rather than re-implementing the RNG call sequence — same numbers,
// no risk of an off-by-one in the port.

typedef struct {
    float a;       // semi-major axis, ball-radius units
    float k;       // flattening b/a
    float tilt;    // major-axis tilt on screen, radians
    float speed;   // turns per second
    float phase;
    float sweep;   // fraction of a full turn actually drawn
    float hue;
    float hue_span;
    float width;   // stroke width, ball-radius units
    float cx, cy;
} arc_seed_t;

extern const arc_seed_t BLOUB_RINGS[6];
extern const arc_seed_t BLOUB_SWOOSH[4];
extern const arc_seed_t BLOUB_COMET_RIBBONS[4];

typedef struct {
    float birth;
    float angle;
    float rho;
} particle_seed_t;

extern const particle_seed_t BLOUB_PARTICLES[5];

#define DOT_X0 (-0.557f)
#define DOT_X1 (-0.013f)
#define DOT_X2 (0.532f)
#define DOT_R 0.165f
#define DOT_PEAK 1.25f

#define NOTIF_ANGLE_DEG (-42.0f)
#define NOTIF_DIST 1.003f
#define NOTIF_R 0.15f
#define NOTIF_POP 1.14f
#define NOTIF_MARGIN 0.054f

#define COMET_DOT 0.129f

/**
 * One rasterized segment of an arc: a capsule stamp in absolute screen
 * coordinates, already coloured, with its bounding box precomputed so a band
 * that the segment does not reach costs four comparisons.
 */
typedef struct {
    capsule_t cap;
    float min_x, max_x, min_y, max_y;
    uint16_t color;     // transport-ordered, full brightness (used when alpha == 255)
    uint16_t color_cpu; // CPU-ordered, for compositing when alpha < 255
    uint8_t alpha;      // the arc's fade, composited per pixel
    bool behind;        // true = must be painted before the body (occluded by it)
} arc_stamp_t;

// 20 left a faint 1.2 px facet on the widest orbit ring (a 252-degree sweep
// at a 199 px semi-major axis). 32 puts the sagitta under half a pixel, and
// short segments are also what the per-row narrowing in draw_stamp likes.
#define ARC_SEGMENTS 32
#define ARC_MAX_STAMPS (ARC_SEGMENTS + 1)

/**
 * Fills `out` with this arc's segments for local/global time `t` (whichever
 * the calling state uses), scaled to pixels and offset to the ball's screen
 * centre. Arcs below `opacity` 0.5 are skipped entirely (there is no alpha
 * blending in the rasterizer, so a fade becomes a pop — cheap and, for a
 * 0.13-0.3s fade, not visually cheap-looking).
 * Returns the number of stamps written (<= ARC_MAX_STAMPS).
 */
int arc_generate_stamps(const arc_seed_t *seed, float t, float scale_px, float origin_x,
                        float origin_y, float opacity, bool swap_color_bytes,
                        arc_stamp_t *out);

typedef struct {
    float x, y; // ball-radius units, relative to ball centre (engine scales to px)
    float r;    // ball-radius units
    float opacity; // 0..1; no alpha blending, so the engine treats < 0.5 as invisible
    bool has_depth;
    float depth; // 0 = fully faded to background, 1 = full foreground colour
} dot_render_t;

#define PARTICLE_MAX_ACTIVE 5

/**
 * Burst particles active at local time `t`, in ball-radius units (pass
 * `scale = 1.0` — poses stay unscaled; the engine scales everything to
 * pixels once, uniformly, at render time). Returns the count written.
 */
int particles_sample(float t, float scale, dot_render_t out[PARTICLE_MAX_ACTIVE]);
