#pragma once

#include <stdint.h>

#include "bloub_shapes.h"

// The customiser's shapes and colours, ported from bloub's src/bot/skins.ts.
//
// These are NOT the animation silhouettes. `bloub_shapes.h`'s profiles are
// measured off the reference video and drive the states that animate their own
// shape; these are built analytically from the original customiser's grid and
// only ever replace the body on a state flagged `base_body`. Two sources, kept
// apart deliberately: the animated states must stay faithful to the video, the
// base shapes are a user's choice.
//
// BLOUB_SHAPE_RADII and BLOUB_COLORS are generated by
// tools/gen_bloub_tables.py. Building them on device would mean shipping the
// superellipse, union-of-discs and rounded-polygon constructors for eight
// values that never change.

#define GROK_SHAPE_COUNT 8
#define GROK_COLOR_COUNT 12

/** r(theta) of each shape, in units of the resting ball radius. */
extern const float BLOUB_SHAPE_RADII[GROK_SHAPE_COUNT][PROFILE_SAMPLES];
extern const char *const BLOUB_SHAPE_NAMES[GROK_SHAPE_COUNT];

/** A palette entry. `rgb565` is CPU-ordered: pass it through bloub_order565. */
typedef struct {
    uint16_t rgb565;
    uint8_t r, g, b;
} bloub_color_t;

extern const bloub_color_t BLOUB_COLORS[GROK_COLOR_COUNT];
extern const char *const BLOUB_COLOR_NAMES[GROK_COLOR_COUNT];
