// Generated by tools/gen_bloub_tables.py -- do not edit by hand.
// Regenerate with: python3 tools/gen_bloub_tables.py
//
// Source of truth: reference/bloub/src/bot/eyefit.ts.

#include "bloub_eyefit.h"

// 37 columns per shape, in this order:
//    0 idle
//    1 idle / neutre
//    2 idle / attentif
//    3 idle / surpris
//    4 idle / excite
//    5 idle / heureux
//    6 idle / hilare
//    7 idle / colere
//    8 idle / triste
//    9 idle / effraye
//   10 idle / mefiant
//   11 idle / confus
//   12 idle / curieux
//   13 idle / fier
//   14 idle / timide
//   15 idle / blase
//   16 idle / somnolent
//   17 wink
//   18 wide
//   19 notify
//   20 swirl
//   21 swirl / neutre
//   22 swirl / attentif
//   23 swirl / surpris
//   24 swirl / excite
//   25 swirl / heureux
//   26 swirl / hilare
//   27 swirl / colere
//   28 swirl / triste
//   29 swirl / effraye
//   30 swirl / mefiant
//   31 swirl / confus
//   32 swirl / curieux
//   33 swirl / fier
//   34 swirl / timide
//   35 swirl / blase
//   36 swirl / somnolent

const float BLOUB_EYEFIT[GROK_SHAPE_COUNT][BLOUB_EYEFIT_COLUMNS][2] = {
    // cercle
    {
        {+0.000000f, +0.000000f}, // idle
        {+0.000000f, +0.000000f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {+0.000000f, +0.000000f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {+0.000000f, +0.000000f}, // idle/mefiant
        {+0.000000f, +0.000000f}, // idle/confus
        {+0.000000f, +0.000000f}, // idle/curieux
        {+0.000000f, +0.000000f}, // idle/fier
        {+0.000000f, +0.000000f}, // idle/timide
        {+0.000000f, +0.000000f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {+0.000000f, +0.000000f}, // wide
        {+0.000000f, +0.000000f}, // notify
        {+0.000000f, +0.000000f}, // swirl
        {+0.000000f, +0.000000f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {+0.000000f, +0.000000f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {+0.000000f, +0.000000f}, // swirl/mefiant
        {+0.000000f, +0.000000f}, // swirl/confus
        {+0.000000f, +0.000000f}, // swirl/curieux
        {+0.000000f, +0.000000f}, // swirl/fier
        {+0.000000f, +0.000000f}, // swirl/timide
        {+0.000000f, +0.000000f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
    // galet
    {
        {-0.011836f, +0.020501f}, // idle
        {-0.011836f, +0.020501f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {-0.000000f, -0.070507f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {+0.000000f, +0.000000f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {-0.000000f, -0.214890f}, // idle/triste
        {-0.000000f, -0.064218f}, // idle/effraye
        {+0.000000f, +0.000000f}, // idle/mefiant
        {+0.260393f, +0.000000f}, // idle/confus
        {-0.035521f, -0.020508f}, // idle/curieux
        {+0.000000f, +0.000000f}, // idle/fier
        {+0.014352f, -0.024859f}, // idle/timide
        {+0.000000f, +0.000000f}, // idle/blase
        {-0.000000f, -0.210000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.017386f, -0.030113f}, // wide
        {+0.010082f, -0.005821f}, // notify
        {-0.011836f, +0.020501f}, // swirl
        {-0.011836f, +0.020501f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {-0.000000f, -0.070507f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {+0.000000f, +0.000000f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {-0.000000f, -0.214890f}, // swirl/triste
        {-0.000000f, -0.064218f}, // swirl/effraye
        {+0.000000f, +0.000000f}, // swirl/mefiant
        {+0.260393f, +0.000000f}, // swirl/confus
        {-0.035521f, -0.020508f}, // swirl/curieux
        {+0.000000f, +0.000000f}, // swirl/fier
        {+0.014352f, -0.024859f}, // swirl/timide
        {+0.000000f, +0.000000f}, // swirl/blase
        {-0.000000f, -0.210000f}, // swirl/somnolent
    },
    // squircle
    {
        {+0.000000f, +0.000000f}, // idle
        {+0.000000f, +0.000000f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {+0.000000f, +0.000000f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {-0.016576f, -0.009570f}, // idle/mefiant
        {+0.000000f, +0.000000f}, // idle/confus
        {+0.000000f, +0.000000f}, // idle/curieux
        {+0.000000f, +0.000000f}, // idle/fier
        {+0.005488f, -0.009505f}, // idle/timide
        {+0.017819f, +0.000000f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.016660f, -0.028855f}, // wide
        {+0.010652f, -0.006150f}, // notify
        {+0.000000f, +0.000000f}, // swirl
        {+0.000000f, +0.000000f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {+0.000000f, +0.000000f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {-0.016576f, -0.009570f}, // swirl/mefiant
        {+0.000000f, +0.000000f}, // swirl/confus
        {+0.000000f, +0.000000f}, // swirl/curieux
        {+0.000000f, +0.000000f}, // swirl/fier
        {+0.005488f, -0.009505f}, // swirl/timide
        {+0.017819f, +0.000000f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
    // capsule
    {
        {-0.044766f, +0.077537f}, // idle
        {-0.044766f, +0.077537f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {-0.105000f, -0.181865f}, // idle/excite
        {-0.105000f, +0.181865f}, // idle/heureux
        {-0.033496f, +0.058017f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {-0.105000f, -0.181865f}, // idle/triste
        {-0.000000f, -0.249108f}, // idle/effraye
        {-0.090933f, +0.052500f}, // idle/mefiant
        {+0.030963f, +0.000000f}, // idle/confus
        {-0.058017f, -0.033496f}, // idle/curieux
        {+0.000000f, +0.080664f}, // idle/fier
        {+0.113419f, -0.065483f}, // idle/timide
        {+0.000000f, +0.000000f}, // idle/blase
        {-0.061569f, -0.035547f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.328689f, -0.189769f}, // wide
        {+0.046789f, +0.000000f}, // notify
        {-0.044766f, +0.077537f}, // swirl
        {-0.044766f, +0.077537f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {-0.105000f, -0.181865f}, // swirl/excite
        {-0.105000f, +0.181865f}, // swirl/heureux
        {-0.033496f, +0.058017f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {-0.105000f, -0.181865f}, // swirl/triste
        {-0.000000f, -0.249108f}, // swirl/effraye
        {-0.090933f, +0.052500f}, // swirl/mefiant
        {+0.030963f, +0.000000f}, // swirl/confus
        {-0.058017f, -0.033496f}, // swirl/curieux
        {+0.000000f, +0.080664f}, // swirl/fier
        {+0.113419f, -0.065483f}, // swirl/timide
        {+0.000000f, +0.000000f}, // swirl/blase
        {-0.061569f, -0.035547f}, // swirl/somnolent
    },
    // triangle
    {
        {-0.003002f, +0.005200f}, // idle
        {-0.003002f, +0.005200f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {-0.010254f, +0.017760f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {-0.105000f, +0.181865f}, // idle/mefiant
        {+0.056172f, +0.032431f}, // idle/confus
        {-0.210000f, +0.000000f}, // idle/curieux
        {-0.027344f, +0.047361f}, // idle/fier
        {+0.000000f, +0.000000f}, // idle/timide
        {+0.000000f, +0.000000f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.147315f, -0.255158f}, // wide
        {+0.197162f, +0.000000f}, // notify
        {-0.003002f, +0.005200f}, // swirl
        {-0.003002f, +0.005200f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {-0.010254f, +0.017760f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {-0.105000f, +0.181865f}, // swirl/mefiant
        {+0.056172f, +0.032431f}, // swirl/confus
        {-0.210000f, +0.000000f}, // swirl/curieux
        {-0.027344f, +0.047361f}, // swirl/fier
        {+0.000000f, +0.000000f}, // swirl/timide
        {+0.000000f, +0.000000f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
    // hexagone
    {
        {+0.000000f, +0.000000f}, // idle
        {+0.000000f, +0.000000f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {+0.000000f, +0.047852f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {-0.015039f, +0.026048f}, // idle/mefiant
        {+0.268356f, +0.000000f}, // idle/confus
        {-0.031969f, -0.018457f}, // idle/curieux
        {-0.017090f, +0.029600f}, // idle/fier
        {+0.016915f, -0.009766f}, // idle/timide
        {+0.009308f, +0.000000f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {+0.000000f, +0.000000f}, // wide
        {+0.013554f, -0.023476f}, // notify
        {+0.000000f, +0.000000f}, // swirl
        {+0.000000f, +0.000000f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {+0.000000f, +0.047852f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {-0.015039f, +0.026048f}, // swirl/mefiant
        {+0.268356f, +0.000000f}, // swirl/confus
        {-0.031969f, -0.018457f}, // swirl/curieux
        {-0.017090f, +0.029600f}, // swirl/fier
        {+0.016915f, -0.009766f}, // swirl/timide
        {+0.009308f, +0.000000f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
    // nuage
    {
        {-0.017075f, +0.029574f}, // idle
        {-0.017075f, +0.029574f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {+0.000000f, +0.000000f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {-0.105000f, +0.181865f}, // idle/mefiant
        {+0.045727f, +0.026401f}, // idle/confus
        {-0.080664f, +0.000000f}, // idle/curieux
        {+0.000000f, +0.000000f}, // idle/fier
        {+0.325652f, -0.188015f}, // idle/timide
        {+0.031067f, +0.017936f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.144685f, -0.250601f}, // wide
        {+0.000000f, +0.000000f}, // notify
        {-0.017075f, +0.029574f}, // swirl
        {-0.017075f, +0.029574f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {+0.000000f, +0.000000f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {-0.105000f, +0.181865f}, // swirl/mefiant
        {+0.045727f, +0.026401f}, // swirl/confus
        {-0.080664f, +0.000000f}, // swirl/curieux
        {+0.000000f, +0.000000f}, // swirl/fier
        {+0.325652f, -0.188015f}, // swirl/timide
        {+0.031067f, +0.017936f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
    // goutte
    {
        {-0.017095f, +0.029609f}, // idle
        {-0.017095f, +0.029609f}, // idle/neutre
        {+0.000000f, +0.000000f}, // idle/attentif
        {+0.000000f, +0.000000f}, // idle/surpris
        {+0.000000f, +0.000000f}, // idle/excite
        {+0.000000f, +0.000000f}, // idle/heureux
        {-0.008203f, +0.014208f}, // idle/hilare
        {+0.000000f, +0.000000f}, // idle/colere
        {+0.000000f, +0.000000f}, // idle/triste
        {+0.000000f, +0.000000f}, // idle/effraye
        {-0.023926f, +0.041441f}, // idle/mefiant
        {+0.046177f, +0.026660f}, // idle/confus
        {+0.000000f, +0.000000f}, // idle/curieux
        {-0.020508f, +0.035521f}, // idle/fier
        {+0.000000f, +0.000000f}, // idle/timide
        {+0.000000f, +0.000000f}, // idle/blase
        {+0.000000f, +0.000000f}, // idle/somnolent
        {+0.000000f, +0.000000f}, // wink
        {-0.126981f, -0.073313f}, // wide
        {+0.041035f, +0.071074f}, // notify
        {-0.017095f, +0.029609f}, // swirl
        {-0.017095f, +0.029609f}, // swirl/neutre
        {+0.000000f, +0.000000f}, // swirl/attentif
        {+0.000000f, +0.000000f}, // swirl/surpris
        {+0.000000f, +0.000000f}, // swirl/excite
        {+0.000000f, +0.000000f}, // swirl/heureux
        {-0.008203f, +0.014208f}, // swirl/hilare
        {+0.000000f, +0.000000f}, // swirl/colere
        {+0.000000f, +0.000000f}, // swirl/triste
        {+0.000000f, +0.000000f}, // swirl/effraye
        {-0.023926f, +0.041441f}, // swirl/mefiant
        {+0.046177f, +0.026660f}, // swirl/confus
        {+0.000000f, +0.000000f}, // swirl/curieux
        {-0.020508f, +0.035521f}, // swirl/fier
        {+0.000000f, +0.000000f}, // swirl/timide
        {+0.000000f, +0.000000f}, // swirl/blase
        {+0.000000f, +0.000000f}, // swirl/somnolent
    },
};

bloub_vec2_t bloub_eyefit(int shape, bloub_state_id_t state, int expr)
{
    const bloub_vec2_t nul = {0.0f, 0.0f};
    if (shape < 0 || shape >= GROK_SHAPE_COUNT) return nul;

    int column;
    switch (state) {
    case STATE_IDLE:
        // the resting face, so one column per expression
        column = (expr >= 0 && expr < BLOUB_EYEFIT_EXPRESSIONS)
                     ? 0 + 1 + expr
                     : 0;
        break;
    case STATE_WINK:
        // a face measured off the video: one column, whatever the expression
        column = 17;
        break;
    case STATE_WIDE:
        // a face measured off the video: one column, whatever the expression
        column = 18;
        break;
    case STATE_NOTIFY:
        // a face measured off the video: one column, whatever the expression
        column = 19;
        break;
    case STATE_SWIRL:
        // the resting face, so one column per expression
        column = (expr >= 0 && expr < BLOUB_EYEFIT_EXPRESSIONS)
                     ? 20 + 1 + expr
                     : 20;
        break;
    default:
        // not a base-body state: the silhouette IS the animation
        return nul;
    }

    bloub_vec2_t v = {BLOUB_EYEFIT[shape][column][0], BLOUB_EYEFIT[shape][column][1]};
    return v;
}
